title: CodeVision Python Training
author: CodeVision Team
logo: CV_White.png
copyright: "2025"

execute:
  execute_notebooks: force

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

repository:
  url: https://github.com/jonbowden/python-training
  path_to_book: "."
  branch: main

html:
  home_page_in_navbar: true
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  use_download_button: true
  extra_footer: |
    <div class="contact-support">
      <a href="https://docs.google.com/forms/d/e/1FAIpQLSc2i2QB27BbkM-uH57wVwYv6HU2QD0paGBjel1cnL4JGMv4SA/viewform" target="_blank">
        <i class="fas fa-comment-dots"></i> Report an Issue or Contact Support
      </a>
    </div>

sphinx:
  config:
    html_static_path: ['_static']
    html_css_files:
      - custom.css
    html_js_files:
      - auth-guard.js
      - notebook-launchers.js
